//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaDeAula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensagem
    {
        public long codigo_mensagem { get; set; }
        public long codigo_turma { get; set; }
        public long codigo_usuario { get; set; }
        public string texto { get; set; }
        public System.DateTime data_postagem { get; set; }
    
        public virtual turma turma { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
