//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaDeAula.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Validation;

    public partial class SalaDeAulaEntities : DbContext
    {
        public SalaDeAulaEntities()
            : base("name=SalaDeAulaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public override int SaveChanges()
        {
            try
            {
                return base.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                string erro = "";

                foreach (var eve in e.EntityValidationErrors)
                {
                    erro += string.Format("Entidade do tipo \"{0}\" no estado \"{1}\" tem os seguintes erros de validação:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        erro = string.Format("\n- Property: \"{0}\", Erro: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }

                throw new DbEntityValidationException(erro);
            }
        }

        public virtual DbSet<alternativa> alternativa { get; set; }
        public virtual DbSet<atividade> atividade { get; set; }
        public virtual DbSet<mensagem> mensagem { get; set; }
        public virtual DbSet<questao> questao { get; set; }
        public virtual DbSet<resposta> resposta { get; set; }
        public virtual DbSet<turma> turma { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_turma> usuario_turma { get; set; }
    }
}
